### ISSUE TITLE
Indiana Jones and the Infernal Machine "hang"

### ISSUE THREAD

**Issue by HelicopterP** [libretro/mupen64plus-libretro-nx#222]
Windows 10
GTX1070
Latest Mupen core from online updater

`mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-angrylion-multithread = "4"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "High"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "Stripped"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Auto"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-DitheringPattern = "False"
mupen64plus-DitheringQuantization = "False"
mupen64plus-EnableCopyAuxToRDRAM = "False"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "FromMem"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "True"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "True"
mupen64plus-EnableNativeResFactor = "0"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "1"
mupen64plus-HybridFilter = "True"
mupen64plus-IgnoreTLBExceptions = "False"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "rumble"
mupen64plus-pak2 = "memory"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-parallel-rdp-dither-filter = "True"
mupen64plus-parallel-rdp-divot-filter = "True"
mupen64plus-parallel-rdp-downscaling = "1/2"
mupen64plus-parallel-rdp-gamma-dither = "True"
mupen64plus-parallel-rdp-native-tex-rect = "True"
mupen64plus-parallel-rdp-native-texture-lod = "False"
mupen64plus-parallel-rdp-overscan = "2"
mupen64plus-parallel-rdp-synchronous = "True"
mupen64plus-parallel-rdp-upscaling = "2x"
mupen64plus-parallel-rdp-vi-aa = "True"
mupen64plus-parallel-rdp-vi-bilinear = "True"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "angrylion"
mupen64plus-RDRAMImageDitheringMode = "False"
mupen64plus-rsp-plugin = "parallel"
mupen64plus-ThreadedRenderer = "False"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "As Is"
mupen64plus-txFilterIgnoreBG = "False"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"`

To reproduce this bug start the game, jump off a cliff and die, then select continue or restart. Retroarch emulator will hang for a minute or two and then it will unfreeze and the game will continue like normal. If you die in fast forward mode, the emulator will not hang and the game will restart as fast as it should. Old Parallel core is unaffected by this bug. I was also unable to reproduce this bug on a standalone Mupen64 plus.

The same bug is also present in Star Wars Battle for Naboo, but it is more annoying to test, because you can't die fast enough in that game.

**Comment by m4xw** [comment]
I will try to repro but probably not a core issue

**Comment by m4xw** [comment]
Oh wait, is its the same issue when shooting a gun?
I did a hack for that years ago, but only for aarch64 if i remember correctly.

**Comment by m4xw** [comment]
Relevant line https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/mupen64plus-core/src/device/r4300/new_dynarec/arm64/assem_arm64.c#L300

**Comment by m4xw** [comment]
Should be fixed in f1283af
Otherwise please reopen 👍

**Comment by HelicopterP** [comment]
I updated all my installed cores via Retroarch online updater, but unfortunatelly this issue isn't fixed. Retroarch still hangs for a minute after reloading a level, but in addition to that now it also hangs when simply starting a level.

**Comment by m4xw** [comment]
So this doesnt happen with cached interpreter?

**Comment by frafes** [comment]
In my tests both Pure and Cached Interperter are working fine

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#572

Both "OldDynarec" and NewDynarec have the same bug, but in NewDynarec it's a "soft-freeze".

**Comment by m4xw** [comment]
Weird, seems the issue is different between aarch64/arm and x64 new_dynarec backends then.
Sad news tho since then I will tag it upstream issue (forgot I even commented on that issue).
Maybe when I finally get some dynarec fixes from the oot issue stuff it will solve itself but I won't actively work on it due to my full schedule.
